version: '3.8'

services:
  producer:
    build: ./producer
    networks:
      - my_network

  consumer:
    build: ./consumer
    depends_on:
      - producer
    networks:
      - my_network
    volumes:
      - logs:/data

networks:
  my_network:

volumes:
  logs:
